name: Create Pull Request

on:
  push:
    branches-ignore:
      - master

jobs:
  creating-PR:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Creating Pull Request
        uses: heitorpolidoro/autocreate-pr@github_token
        env:
          HEITORPOLIDORO: ${{ secrets.AUTOCREATE_PR_HEITORPOLIDORO }}